// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtczA7nl71w0jlVqWZAYjXkEFl-RRjbuM',
    appId: '1:832562754432:web:4fb3af835c4f07f3e10765',
    messagingSenderId: '832562754432',
    projectId: 'fir-practice-c5060',
    authDomain: 'fir-practice-c5060.firebaseapp.com',
    storageBucket: 'fir-practice-c5060.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY0SshF97D2V3ZUmZHPswWE8yG-Twyk4k',
    appId: '1:832562754432:android:025bd07b2e06ee0fe10765',
    messagingSenderId: '832562754432',
    projectId: 'fir-practice-c5060',
    storageBucket: 'fir-practice-c5060.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx4-ezxjl-Q_ZZQTuW_VwDdClzg_ku6xY',
    appId: '1:832562754432:ios:042bab7a99ce3ae5e10765',
    messagingSenderId: '832562754432',
    projectId: 'fir-practice-c5060',
    storageBucket: 'fir-practice-c5060.appspot.com',
    iosClientId: '832562754432-018jj3c913i7e0ststjs4b1c58ie5mie.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseRenkeiTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx4-ezxjl-Q_ZZQTuW_VwDdClzg_ku6xY',
    appId: '1:832562754432:ios:042bab7a99ce3ae5e10765',
    messagingSenderId: '832562754432',
    projectId: 'fir-practice-c5060',
    storageBucket: 'fir-practice-c5060.appspot.com',
    iosClientId: '832562754432-018jj3c913i7e0ststjs4b1c58ie5mie.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseRenkeiTest',
  );
}
